# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChocolateShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChocolateShop

pod 'Firebase/Database'
pod 'Firebase/Core'


pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/RemoteConfig'
pod 'Firebase/AdMob'
pod 'Kingfisher'
pod 'ImageSlideshow'
pod "ImageSlideshow/Kingfisher"

end
